---
title: "7_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pacman)
p_load(tidyverse, scales, ggwordcloud, ggunchained)
```


1: SEE HOW SPEECHES WERE RATED BY MODEL

```{r compare metrics and speeches}
## original data
full <- read_csv("data/csv/full_ref.csv") %>%
  select(-text_c, -speaker_index, -bod_index, -hhmm)

## lda_output + novelty, resonance
ntr <- list.files(path = "data/ntr", pattern = "_from_5k", full.names = T)

read_csv_and_assign <- function(path) {
  subset <- read_csv(path) %>%
    mutate(group = str_extract(path, "\\d"))
}

comparison <- map_df(ntr, read_csv_and_assign) %>%
  rename(rowname = doc_id) %>%
  arrange(rowname) %>%
  left_join(full, by = "rowname")

```

# OVERALL PATTERNS
```{r ploting}
# NOVELTY VS RESONANCE
ggplot(comparison, aes(novelty, resonance)) +
    geom_bin2d(bins = 100) +
    scale_fill_viridis_c(trans = "log", breaks = c(1,10,100,1000),
                         labels = trans_format("log10", 
                                               math_format(expr = 10^.x, format = force))) +
    geom_smooth(method = "lm", colour = "black", alpha = 0, size = 0.5) +
    labs(x = "Novelty\n", y = "Resonance", 
         title = "Resonance vs. Novelty",
         subtitle = "with regression line, w = 5000",
         caption = "Data source: speeches in Czech Chamber of Deputies (2010-2019)") +
  scale_x_continuous(breaks = seq(0, 5, 1)) +
  scale_y_continuous(breaks = seq(-3, 3, 1)) +
  theme_janco_point() +
  theme(legend.direction = "vertical", legend.position = "right",
        plot.caption = element_text(hjust = 0.5)
        )


# NOVELTY VS TRANSIENCE
ggplot(comparison, aes(novelty, transience)) +
    geom_bin2d(bins = 100) +
    scale_fill_viridis_c(trans = "log", breaks = c(1,10,100,1000,10000),
                         labels = trans_format("log10", math_format(expr = 10^.x, format = force))) +
    geom_abline(colour = "black", linetype = "dashed") +
    labs(x = "Novelty\n", y = "Transience", 
         title = "Novelty vs. Transience",
         subtitle = "with identity line (x = y), w = 27",
         caption = "Data source: speeches in Czech Chamber of Deputies (2010-2019)") +
  scale_x_continuous(breaks = seq(0, 6, 1)) +
  scale_y_continuous(breaks = seq(0, 6, 1)) +
  theme_janco_point() +
  theme(legend.direction = "vertical", legend.position = "right",
        plot.caption = element_text(hjust = 0.5)
        )


```

# BY PARTY
```{r party pre}
pc <- comparison %>%
  mutate(zkratka = ifelse(is.na(zkratka), "Guest Speakers", zkratka)) %>%
  mutate(party = case_when(zkratka == "ANO2011" ~ "Babiš et al.",
                           zkratka == "CSSD" ~ "SocDem",
                           zkratka == "KDU-ČSL" ~ "ChristDem",
                           zkratka == "KSCM" ~ "Commies",
                           zkratka == "ODS" ~ "Conservatives",
                           zkratka == "TOP09" ~ "Big-City-Liberals",
                           zkratka == "STAN" ~ "Village-Liberals",
                           zkratka == "Piráti" ~ "Pirates",
                           zkratka == "Usvit" | zkratka == "SPD" ~ "Nazis",
                           zkratka == "VV" ~ "Catch-all"))

party_colors =  c("#034ea2", "#6b3362", "#e00219", "#ec5800",
                  "#00aeef", "#8f9093", "#272660", "#ffd700",
                  "#1176bc", "#1176bc", "#000000", "#7ec192")

names(party_colors) = unique(pc$zkratka)

```

```{r party plots}
# by party nov-res line
pc %>%
  filter(group == 3) %>%
  ggplot(aes(novelty, resonance, color = zkratka)) +
  geom_smooth(alpha = 0) +
  scale_color_manual(values = party_colors, aesthetics = "color") +
  theme_janco_point()

pc %>%
  filter(group == 4) %>%
  ggplot(aes(novelty, resonance, color = zkratka)) +
  geom_smooth(alpha = 0) +
  scale_color_manual(values = party_colors, aesthetics = "color") +
  theme_janco_point()


# by party nov-res density
pc %>%
  filter(group == 3) %>%
  ggplot(aes(novelty, resonance)) +
  geom_bin2d(bins = 100) +
  scale_fill_viridis_c(trans = "log", breaks = c(1,10,100,1000,10000),
                         labels = trans_format("log10", math_format(expr = 10^.x, format = force))) +
  geom_smooth(method = "lm", colour = "black", size = 0.5) +
  facet_wrap(~zkratka) +
  theme_janco_point()

pc %>%
  filter(group == 8) %>%
  ggplot(aes(z_novelty, z_resonance)) +
  geom_bin2d(bins = 100) +
  scale_fill_viridis_c(trans = "log", breaks = c(1,10,100,1000,10000),
                         labels = trans_format("log10", math_format(expr = 10^.x, format = force))) +
  geom_smooth(method = "lm", colour = "black", size = 0.5) +
  facet_wrap(~zkratka) +
  theme_janco_point()


# split-violin plot comparing bellow- and above- average novely to transience across parties
pc %>%
  mutate(hi_novelty = ifelse(z_novelty >= 0, 1, 0)) %>%
  ggplot(aes(party, transience, fill = factor(hi_novelty))) +
  geom_split_violin() +
  theme_janco_bar()

```



# TABLE OF PER-X TOPS
```{r per speaker}
per_speaker = comparison %>%
    group_by(speaker) %>%
    summarise(n = n(),
              `z(Novelty)` = mean(z_novelty),
              `z(Transience)` = mean(z_transience),
              `z(Resonance)` = mean(z_resonance)
              )

per_speaker %>%
    arrange(-`z(Novelty)`) %>%
    filter(n >= 10) %>%
    head(10) %>%
    knitr::kable()


# round(stat.desc(nchar(comparison$text)), 2)
# rethinking::dens(nchar(comparison$text))

```

```{r per party}
per_party = comparison %>%
    group_by(zkratka) %>%
    summarise(n = n(),
              `z(Novelty)` = mean(z_novelty),
              `z(Transience)` = mean(z_transience),
              `z(Resonance)` = mean(z_resonance)
              )

per_party %>%
    arrange(-`z(Resonance)`) %>%
    filter(n >= 10) %>%
    head(10) %>%
    knitr::kable()

```

