---
title: "7_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pacman)
p_load(tidyverse, scales, ggwordcloud, ggunchained)
```


1: SEE HOW SPEECHES WERE RATED BY MODEL

```{r compare metrics and speeches}
## original data
full <- read_csv("data/csv/full_lemma_in.csv") %>%
  select(-text_c)

## lda_output + novelty, resonance
ntr <- list.files(path = "data/ntr", pattern = "_from", full.names = T)

comparison <- map_df(ntr, read_csv) %>%
  rename(rowname = doc_id) %>%
  arrange(rowname) %>%
  left_join(full, by = "rowname")

```


```{r ploting}
# NOVELTY VS RESONANCE
ggplot(comparison, aes(novelty, resonance)) +
    geom_bin2d(bins = 50) +
    scale_fill_viridis_c(trans = "log", breaks = c(1,10,100,1000),
                         labels = trans_format("log10", 
                                               math_format(expr = 10^.x, format = force))) +
    geom_smooth(method = "lm", colour = "black", linetype = "dashed", alpha = 0) +
    labs(x = "Novelty", y = "Resonance", 
         title = "Resonance vs. Novelty") +
  scale_x_continuous(breaks = seq(1, 6, 1)) +
  scale_y_continuous(breaks = seq(-3, 3, 1)) +
  theme_janco_point()


# NOVELTY VS TRANSIENCE
ggplot(comparison, aes(novelty, transience)) +
    geom_bin2d(bins = 50) +
    scale_fill_viridis_c(trans = "log", breaks = c(1,10,100,1000,10000),
                         labels = trans_format("log10", math_format(expr = 10^.x, format = force))) +
    geom_smooth(method = "lm", colour = "black", linetype = "dashed",  alpha = 0) +
    labs(x = "Novelty", y = "Transience", 
         title = "Resonance vs. Transience") +
  scale_x_continuous(breaks = seq(0, 6, 1)) +
  scale_y_continuous(breaks = seq(0, 6, 1)) +
  theme_janco_point()


```

```{r per speaker}
per_speaker = comparison %>%
    group_by(speaker) %>%
    summarise(n = n(),
              `z(Novelty)` = mean(z_novelty),
              `z(Transience)` = mean(z_transience),
              `z(Resonance)` = mean(z_resonance)
              )

per_speaker %>%
    arrange(-`z(Novelty)`) %>%
    filter(n >= 10) %>%
    head(10) %>%
    knitr::kable()


```
