---
title: "parse_transcript"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pacman)
p_load(tidyverse, rvest, zoo)
```

# parse_stenoskript function
```{r}
parse_stenoskript <- function(html_doc) {
  
  link <- read_html(html_doc)
  
  # IMPORT DATA
  raw_xml <- link %>%
    html_nodes("p") %>%
    as.character() %>%
    enframe(name = NULL) %>%
    rename(xml = value)
  
  text <- link %>%
    html_nodes("p") %>%
    html_text() %>%
    enframe(name = NULL) %>%
    rename(text = value)
  
  doc <- link %>%
    html_node("title") %>%
    html_text() %>%
    enframe(name = NULL) %>%
    rename(doc = value)
  
  # EXTRACT INFORMATION
  prep1 <- cbind.data.frame(raw_xml, text, doc) %>%
    # extracting speaker
    mutate(speaker = str_extract(xml, "<a.*?</a>"),
           speaker = str_extract(speaker, ">.*?<"),
           speaker = str_remove_all(speaker, "<|>"),
           speaker_index = if_else(is.na(speaker), 0, 1)) %>%
    # extracting meeting point
    mutate(bod = ifelse(str_detect(xml, 'align="center'), text, NA),
           bod = ifelse(bod == " ", NA, bod),
           bod_index = if_else(is.na(bod), 0, 1)) %>%
    # extractking scenic notes
    mutate(com = str_extract_all(text, "\\((.*?)\\)"),
           com = paste0(com),
           com = ifelse(com == "character(0)", NA, com)) %>%
    # extract meeting time
    mutate(hhmm = ifelse(str_detect(com, "hodin"), 
                         str_extract(com, "\\d\\d\\.\\d\\d|\\d.\\d\\d"), NA))
  
  # EXTRACT LIST OF SPEAKERS
  # possible tweak: if speaker_index is 0, don't run these lines
  list_of_speakers <- enframe(table(prep1$speaker))$name
  list_of_speakers <- paste0(list_of_speakers, ":")
  
  
  # CLEANING INFORMATION
  prep2 <- prep1 %>%
    # clean the astrisks 
    mutate(text = str_remove(text, "\\*\\*\\*")) %>%
    # erasing empty rows (whitespace or nothing)
    mutate(text = trimws(text, which = "both"),
           text = ifelse(nchar(text) <= 1, NA, text)) %>%
    filter(!is.na(text)) %>%
    # erasing comments from text
    mutate(text = str_remove_all(text, "\\((.*?)\\)")) %>%
    # easting speaker name from text
    mutate(text = ifelse(speaker_index == 1, 
                         str_remove(text, paste(list_of_speakers, collapse = "|")), 
                         text))
  
  
  # GET READY FOR MERGING
  prep3 <- prep2 %>%
    # filling NAs for speaker
    mutate(speaker = na.locf(speaker, na.rm = F)) %>%
    # filling NAs for bod
    mutate(bod = na.locf(bod, na.rm = F)) %>%
    # correct variables
    mutate(xml = as.character(xml),
           text = as.character(text),
           doc = as.character(doc),
           speaker = as.character(speaker),
           speaker_index = as.numeric(speaker_index),
           bod = as.character(bod),
           bod_index = as.character(bod_index),
           com = as.character(com),
           hhmm = as.character(hhmm))
  
  return(prep3)
}
```


# list of objects
```{r}
s2017 <- list.files(path = "data/2017ps/", pattern = "s", full.names = T)
s2013 <- list.files(path = "data/2013ps/", pattern = "s", full.names = T)
s2010 <- list.files(path = "data/2010ps/", pattern = "s", full.names = T)
```


# run parsing
```{r}
psp2017r <- map_df(s2017, parse_stenoskript)
write_csv(psp2017r, "data/csv/psp2017_rawish.csv")

psp2013r <- map_df(s2013, parse_stenoskript)
write_csv(psp2013r, "data/csv/psp2013_rawish.csv")

psp2010r <- map_df(s2010, parse_stenoskript)
write_csv(psp2010r, "data/csv/psp2010_rawish.csv")
```


# Postprocessing of metadata (na.locf)
```{r}
psp2017 <- psp2017r %>%
  # filling NAs for speaker
  mutate(speaker = na.locf(speaker, na.rm = F)) %>%
  # filling NAs for bod
  mutate(bod = na.locf(bod, na.rm = F)) %>%
  # filter bod rows
  filter(bod_index == 0) %>%
  # get rid of xml
  select(-xml)

write_csv(psp2017, "data/csv/psp2017.csv")


psp2013 <- psp2013r %>%
  # filling NAs for speaker
  mutate(speaker = na.locf(speaker, na.rm = F)) %>%
  # filling NAs for bod
  mutate(bod = na.locf(bod, na.rm = F)) %>%
  # filter bod rows
  filter(bod_index == 0) %>%
  # get rid of xml
  select(-xml)

write_csv(psp2013, "data/csv/psp2013.csv")


psp2010 <- psp2010r %>%
  # filling NAs for speaker
  mutate(speaker = na.locf(speaker, na.rm = F)) %>%
  # filling NAs for bod
  mutate(bod = na.locf(bod, na.rm = F)) %>%
  # filter bod rows
  filter(bod_index == 0) %>%
  # get rid of xml
  select(-xml)

write_csv(psp2010, "data/csv/psp2010.csv")
```

